### ISSUE TITLE
Basic & Bearer Authentication

### ISSUE THREAD

**Issue by hanorine** [OscarYuen/go-graphql-example#22]
I have used the suggestive [blitter.se](https://www.blitter.se/utils/basic-authentication-header-generator/). The generated basic gives me an error of not being long enough.

`2018/12/29 15:43:25 crypto/bcrypt: hashedSecret too short to be a bcrypted password`

The `Bearer` example in the graphql.html file is obviously tailored for an example you had used.

I would suggest a clearer explanation of how you generated the Basic Authorization key.  Is this possible in the near future?

**Comment by hanorine** [comment]
I tracked the issue down to the following [code section](https://github.com/OscarYuen/go-graphql-starter/blob/master/service/user_service.go#L32). 

```
func (u *UserService) FindByEmail(email string) (*model.User, error) {
	user := &model.User{}

	userSQL := `SELECT * FROM users WHERE email = $1`
	udb := u.db.Unsafe()
	row := udb.QueryRowx(userSQL, email) // <- here
	err := row.StructScan(user)
	if err == sql.ErrNoRows {
		return user, nil
	}
	if err != nil {
		u.log.Errorf("Error in retrieving user : %v", err)
		return nil, err
	}

	roles, err := u.roleService.FindByUserId(&user.ID)
	if err != nil {
		u.log.Errorf("Error in retrieving roles : %v", err)
		return nil, err
	}
	user.Roles = roles
	return user, nil
}
```

I would not receive anything from the db.
I changed it to:

```
u.db.Get(user, `SELECT id, email, password FROM users WHERE email = $1`, email)
```

Furthermore, I had to change the psql type of password from bytes to varchar. This guaranteed a return that is more aligned to the code you have provided.

and removed the errors. This got me an access_token and solved the issues.

Concerning the "Bearer" authentication, I would suggest you add some documentation that the token returned from user creation is the same token used for the `graphql.html` headers example of the `Authorization` value. I figured I'd try and see if it would work.

luckily for me it did.

**Comment by OscarYuen** [comment]
@JaysQubeXon Thanks for your investigation. I would try to add more explanation on it. Thanks.
